### ISSUE TITLE
把merge CNN into FC是完全等价的吗？

### ISSUE THREAD

**Issue by Fengwills** [DingXiaoH/RepMLP#1]
把merge CNN into FC是完全等价的吗？
还是像formulation部分说的一种输入输出维度相同的替换？
如果是完全等价，可否在训练阶段也去掉CNN？

**Comment by DingXiaoH** [comment]
是完全等价的，但我不知道第二句的意思是什么。训练阶段去掉，性能就会变差，这在实验的第一节已经展示了。



***@***.***
 
发件人： will
发送时间： 2021-05-11 11:25
收件人： DingXiaoH/RepMLP
抄送： Subscribed
主题： [DingXiaoH/RepMLP] 把merge CNN into FC是完全等价的吗？ (#1)
把merge CNN into FC是完全等价的吗？
还是像formulation部分说的一种输入输出维度相同的替换？
如果是完全等价，可否在训练阶段也去掉CNN？

**Comment by Fengwills** [comment]
> 是完全等价的，但我不知道第二句的意思是什么。训练阶段去掉，性能就会变差，这在实验的第一节已经展示了。 ***@***.*** 发件人： will 发送时间： 2021-05-11 11:25 收件人： DingXiaoH/RepMLP 抄送： Subscribed 主题： [DingXiaoH/RepMLP] 把merge CNN into FC是完全等价的吗？ (#1) 把merge CNN into FC是完全等价的吗？ 还是像formulation部分说的一种输入输出维度相同的替换？ 如果是完全等价，可否在训练阶段也去掉CNN？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

论文中formulation 部分说的CONV替换成MMUL，其实只是输入输出为度相同，过程并不相同吧。如果完全等价的话，按理说，在训练阶段去掉也可以吧。实验第一节是指在训练阶段也去掉了CNN？完全不加local perceptron这部分？只保留global perceptron 和 partition perceptron？

**Comment by DingXiaoH** [comment]
是完全等价的。
去掉的话效果会变差。这在实验第一节展示了。



***@***.***
 
发件人： will
发送时间： 2021-05-11 11:25
收件人： DingXiaoH/RepMLP
抄送： Subscribed
主题： [DingXiaoH/RepMLP] 把merge CNN into FC是完全等价的吗？ (#1)
把merge CNN into FC是完全等价的吗？
还是像formulation部分说的一种输入输出维度相同的替换？
如果是完全等价，可否在训练阶段也去掉CNN？
