### ISSUE TITLE
人脸识别是否加CosFace、ArcFace之类的

### ISSUE THREAD

**Issue by bixiwen** [DingXiaoH/RepMLP#4]
您好，请问下，您们的RepMLP用于人脸识别时是否加CosFace、ArcFace之类的？输入只用了96*96，是否用过112*112？
谢谢！

**Comment by DingXiaoH** [comment]
您好，只用的AM-Softmax loss。
没有用别的数据，也没有用112

**Comment by bixiwen** [comment]
@DingXiaoH 好的，谢谢。能否提供下完整的训练代码？一般训练过程为：train->test->train，当test时使用 repmlp.switch_to_deploy()，之后再train时如何转回来？
