### ISSUE TITLE
提问:Cifar10的训练集合和测试集合的划分标准

### ISSUE THREAD

**Issue by fengyuanyu1** [DingXiaoH/RepMLP#5]
丁学长您好,之前看到您在文章中写到使用Cifar数据集来进行一致性的验证。
我想复现一下这个结果,但是Readme中好像并没有告知关于Cifar训练集和测试集的切分细节,以及它的输入维度。
这个能告知一下吗?

**Comment by DingXiaoH** [comment]
你好

就是cifar的常规用法，50000/10000, 32x32，这里没有调参所以没有验证集

Regards，
丁霄汉



***@***.***
 
发件人： Yuandao
发送时间： 2021-07-24 10:38
收件人： DingXiaoH/RepMLP
抄送： Subscribed
主题： [DingXiaoH/RepMLP] 提问:Cifar10的训练集合和测试集合的划分标准 (#5)
丁学长您好,之前看到您在文章中写到使用Cifar数据集来进行一致性的验证。
我想复现一下这个结果,但是Readme中好像并没有告知关于Cifar训练集和测试集的切分细节,以及它的输入维度。
这个能告知一下吗?

**Comment by fengyuanyu1** [comment]
好的，感谢
