### ISSUE TITLE
Why not keep repmlp-resnet?

### ISSUE THREAD

**Issue by twmht** [DingXiaoH/RepMLP#9]
This design of repmlp-resnet is different from the lastest repmlpnet, and it shows great face recognition accuracy.

why not keep repmlp-resnet in this repo?

**Comment by DingXiaoH** [comment]
Because we think using RepMLPBlock in ResNet to make a hybrid model is not cool. A pure MLP model is cooler. 
And we do not use it on face recognition anymore because many face datasets have been banned due to privacy issues.
